CREATE TABLE "my-chatbot_account" (
	"id" text PRIMARY KEY NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"user_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"id_token" text,
	"access_token_expires_at" timestamp,
	"refresh_token_expires_at" timestamp,
	"scope" text,
	"password" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "my-chatbot_chats" (
	"id" varchar(256) PRIMARY KEY NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "my-chatbot_messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"role" varchar(256) NOT NULL,
	"content" text,
	"parts" jsonb NOT NULL,
	"chatId" varchar(256)
);
--> statement-breakpoint
CREATE TABLE "my-chatbot_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "my-chatbot_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "my-chatbot_session" (
	"id" text PRIMARY KEY NOT NULL,
	"expires_at" timestamp NOT NULL,
	"token" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"user_id" text NOT NULL,
	CONSTRAINT "my-chatbot_session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "my-chatbot_user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean NOT NULL,
	"image" text,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL,
	CONSTRAINT "my-chatbot_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "my-chatbot_verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp,
	"updated_at" timestamp
);
--> statement-breakpoint
ALTER TABLE "my-chatbot_account" ADD CONSTRAINT "my-chatbot_account_user_id_my-chatbot_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."my-chatbot_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "my-chatbot_messages" ADD CONSTRAINT "my-chatbot_messages_chatId_my-chatbot_chats_id_fk" FOREIGN KEY ("chatId") REFERENCES "public"."my-chatbot_chats"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "my-chatbot_session" ADD CONSTRAINT "my-chatbot_session_user_id_my-chatbot_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."my-chatbot_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "my-chatbot_post" USING btree ("name");